### ISSUE TITLE
qgis cask gets overwritten by official cask

### ISSUE THREAD

**Issue by beingalink** [DingoBits/homebrew-dingobits#1]
To reproduce:

- brew tap dingobits/dingobits
- brew install --cask dingobits/dingobits/qgis
- brew upgrade

==> the dingobits qgis version gets overwritten by the official (x86) cask which is versioned as 3.28.1,20221118_122921

**Comment by eatyourbaby** [comment]
Didn't think it through... I've updated the name to `qgis-arm64`. Thanks!

**Comment by beingalink** [comment]
Thank you!
